---

- name: Set Test ID
  set_fact:
    test_id: '1.4.2'

- name: "{{ test_id }}.check"
  shell: |
    cf_status=$(crm_attribute -t crm_config -G -n concurrent-fencing --quiet)
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        if [[ ${cf_status} = "true" ]]; then
            echo "correct"
        else
           echo "${cf_status}"
        fi
    else
        echo "fence_azure_arm not configured"
    fi
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- block:
    - import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
  when:
    - ansible_check_mode

