---

id: 1.1.7
name: Corosync expected_votes parameter is set to {{ expected[id] }}
group: Corosync
labels: generic
description: |
  Test if the configured corosync expected_votes parameter has the correct value: {{ expected[id] }}
remediation: |
  ## Remediation
  Adjust the corosync `expected_votes` parameter to `2` to make sure pacemaker calculates the actions properly for a two-node cluster.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"

# Test data
key_name: expected_votes
