---

name: 1.1.4
group: Corosync
labels: generic
description: |
  The configured corosync join parameter has the correct value: {{ expected[name] }}
remediation: |
  ## Remediation
  Adjust the Corosync `join` parameter as recommended on the Azure best practices.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# Test data
key_name: join

# check id. This value must not be changed over the life of this check
id: 24ABCB
