---

id: 2.2.9
name: SAP Host Agent is installed
group: OS and package versions
labels: hana
description: |
  Test if the SAP Host Agent is installed
remediation: |
  ## Abstract
  SAP Host Agent should be installed on all cluster nodes

  ## Remediation
  Install SAP Host Agent. Follow confluence link to the relevant section of the Best Practice/Setup Guide.

  ## Reference
  - Section 6.1 in https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-installing-the-sap-hana-databases-on-both-cluster-nodes
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
