---

id: 1.2.1
name: Fencing is enabled
group: Pacemaker
labels: generic
description: |
  Test if fencing is enabled in the cluster attributes
remediation: |
  ## Abstract
  Fencing is mandatory to guarantee data integrity for your SAP Applications.
  Running a HA Cluster without fencing is not supported and might cause data loss.
  ## Remediation
  Execute the following command to enable it:
  ```
  crm configure property stonith-enabled=true
  ```
  ## References
  - T.B.D.
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
