---

expected:
  "1.1.1": "5000"
  "1.1.2": "6000"
  "1.1.3": "20"
  "1.1.4": "60"
  "1.1.5": "10"
  "1.1.6": ""
  "1.1.7": "2"
  "1.1.8": "1"
  "1.2.1": "true"
  "1.2.2.sbd": ""
  "1.2.2.fence_azure_arm": ""
  "1.3.1": "yes"
  "1.3.2": "always"
  "1.3.3": "enabled"
  "1.3.4": "1"
  "1.3.5": "5"
  "1.3.6": "10"
