---

id: 1.3.3
name: SBD service is enabled
group: SBD
labels: generic
description: |
  Test if the SBD service is enabled
remediation: |
  ## Abstract
  If not enabled, SBD service will not start automatically after reboots, affecting the correct cluster startup.

  ## Remediation
  To enable the service, run:
  ```
  systemctl enable sbd
  ```

  ## References
  - T.B.D.
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
