version: '3'

services:

  consul-server-1:
    image: consul:latest
    networks:
      - trento
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul-server-2:
    image: consul:latest
    networks:
      - trento
    command: "agent -server -retry-join consul-server-1 -client 0.0.0.0"

  consul-server-3:
    image: consul:latest
    networks:
      - trento
    command: "agent -server -retry-join consul-server-1 -client 0.0.0.0"

  trento-web:
    build: .
    image: trento:latest
    networks:
      - trento
    ports:
      - "8080:8080"
    environment:
      - CONSUL_HTTP_ADDR=consul-server-1:8500
    command: "web serve -p 8080"

networks:
  trento:
