---

- name:  "{{ name }} get corosync configuration file content"
  command: md5sum /etc/corosync/corosync.conf
  register: corosync_md5_content
  check_mode: false
  changed_when: false

- name: "{{ name }} set corosync configuration file content"
  set_fact:
    corosync_file_md5: "{{ corosync_md5_content.stdout }}"
  delegate_facts: true

- name: "{{ name }}.check"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='corosync_file_md5') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
