---

- name: set_global_results {{ id }}
  set_fact:
    results: |
      {{ (results | default({})) | combine(
        {
          'results': {
            item: {
              'checks': {
                id: {
                  'hosts': {
                    inventory_hostname: {
                      'result': status
                    }
                  }
                }
              }
            }
          }
        }, recursive=True)
      }}
  delegate_to: localhost
  with_items: "{{ group_names }}"
