- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 2.2.5.exclude
    name: Check SBD version is not
    group: OS and package versions
    labels: hana
    description: |
      Test if installed SBD version is not {{ expected['2.2.5.exclude'] }}
    remediation: |
      ## Abstract
      Installed SBD version must not be equal than {{ expected['2.2.5.exclude'] }}

      ## Remediation
      Install or upgrade to a supported SBD version

      ## Reference
      - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
    implementation: "{{ lookup('file', 'roles/'+id+'/tasks/main.yml') }}"
