- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 2.2.10
    name: HANA's autostart is disabled
    group: OS and package versions
    labels: hana
    description: |
      Test if HANA's autostart value is disabled
    remediation: |
      ## Abstract
      Automated start of SAP HANA instances during system boot must be switched off

      ## Remediation
      1. Log on to the SAP HANA host as a user with root authorization.
      2. Change to the system profile directory /usr/sap/<SID>/SYS/profile.
      3. Edit the profile <SID>_HDB<instance number>_<host name>.
      4. Change the parameter setting Autostart = 1 to Autostart = 0 .
      5. Save the profile <SID>_HDB<instance number>_<host name>.

      ## References
      - Section 2 in https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#cha.hana-sr.scenario
    implementation: "{{ lookup('file', 'roles/'+id+'/tasks/main.yml') }}"
