apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trento-runner.fullname" . }}
  labels:
    {{- include "trento-runner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trento-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trento-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trento-runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - runner
            - start
            - --log-level
            - {{ .Values.global.logLevel }}
            - --ara-server
            - http://{{ .Release.Name }}-{{ .Values.dependencies.ara.name }}:{{ .Values.dependencies.ara.port }}
            - --api-host
            - {{ .Release.Name }}-{{ .Values.dependencies.trentoWeb.name }}
            - --api-port
            - "{{ .Values.dependencies.trentoWeb.port }}"
            - -i
            - "{{ .Values.checkIntervalMins }}"
          env:
            - name: CONSUL_HTTP_ADDR
              value: {{ .Release.Name }}-{{ .Values.dependencies.consul.name }}:{{ .Values.dependencies.consul.port }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: sshconfig
            mountPath: "/root/.ssh"
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: sshconfig
        secret:
          secretName: {{ include "trento-runner.fullname" . }}-privatekey
          defaultMode: 0400
          items:
          - key: privatekey
            path: id_rsa
