### Global Values ###
global:
  logLevel: info

### Sub Charts Specific Values ###
trento-web:
  nameOverride: web
  enabled: true

trento-runner:
  nameOverride: runner
  enabled: true
  dependencies:
    trentoWeb:
      name: web

ara:
  enabled: true

postgresql:
  enabled: true
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlDatabase: "trento"
