---

- name: Set Test ID
  set_fact:
    test_id: '1.5.2'

- name: "{{ test_id }}.check"
  shell: |
    function attempt_login {
      /usr/bin/expect << 'EOF'
      set timeout 5
      spawn ssh -o "StrictHostKeyChecking no" hacluster@127.0.0.1 :
      expect "assword:"
      send -- "linux\r"
      expect {
        "assword:" { exit 1}
        eof { exit 0 }
      }
      foreach {pid spawnid os_error_flag value} [wait] break
      exit $value
    EOF
    return $?
    }
    # The test fails if we could successfully log into hacluster
    $(attempt_login) && exit 1
    exit 0
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1
  

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
