- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 1.5.2
    name: hacluster password is changed from default 'linux'
    group: Miscellaneous
    labels: generic
    description: |
      Test if the cluster hacluster user password has been change from default 'linux'
    remediation: |
      ## Abstract
      The password of the hacluster user should be changed after setting
      up the clsuter

      ## Remediation
      ```sudo passwd hacluster```
      
      ## References
      - section 9.1.2 https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
    implementation: "{{ lookup('file', 'roles/'+id+'/tasks/main.yml') }}"
