---

- name: Set Test ID
  set_fact:
    test_id: '1.3.2'

- name: "{{ test_id }}.check"
  shell: 'grep SBD_STARTMODE /etc/sysconfig/sbd'
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
