name: 'Deploy'
description: 'Deploy trento'
inputs:
  role:
    description: 'Trento role'
    required: true
    default: 'agent'
runs:
  using: "composite"
  steps:
    - name: stop trento
      run: sudo systemctl stop trento-${{ inputs.role }}
      shell: bash
    # The trento runner goes in the same machine than the web
    - name: stop trento runner
      run: |
        if [ "${{ inputs.role }}" = "web" ]; then
          systemctl stop trento-runner
        fi
      shell: bash
    - name: uncompress
      run: |
        gunzip -f trento-amd64.gz
        mv trento-amd64 trento
      shell: bash
    - name: chmod
      run: chmod +x trento
      shell: bash
    - name: deploy binary
      run: rsync -av trento /srv/trento/
      shell: bash
    - name: start consul
      run: sudo systemctl start consul
      shell: bash
    - name: start trento
      run: sudo systemctl start trento-${{ inputs.role }}
      shell: bash
    # The trento runner goes in the same machine than the web
    - name: start trento runner
      run: |
        if [ "${{ inputs.role }}" = "web" ]; then
          systemctl start trento-runner
        fi
      shell: bash
