- hosts: all
  gather_facts: false
  ignore_errors: yes
  become: yes

  vars:
    ara_playbook_labels:
      - test

  tasks:
    - name: require check mode
      fail:
         msg: "Only supported for --check option"
      when:
        - not ansible_check_mode

    - block:
        - name: Include load_facts
          import_role:
            name: load_facts
          register: result

        - name: count unreachable hosts number
          set_fact:
            unreachable_count: |
              {{ unreachable_count|default(0)|int + 1 }}
          when: facts_result is unreachable
          delegate_to: localhost

        - name: Post initial empty results to ARA if all hosts are unreachable
          import_role:
            name: post-results
            tasks_from: post
          when: unreachable_count|default(0)|int == hostvars|length

      ignore_unreachable: yes

    - name: Find checks
      find:
        paths: "{{ playbook_dir}}/roles/checks"
        file_type: directory
      register: checks
      run_once: yes
      delegate_to: localhost

    - name: Run check
      include_role:
        name: "{{ item.path }}"
      loop: "{{ checks.files }}"
      when: "{{ (item.path | basename) in cluster_selected_checks }}"

  post_tasks:
    - name: Post results
      import_role:
        name: post-results
        tasks_from: post
