---

name: 2.1.7
group: SAP HANA System Replication Resource Agent
labels: hana
description: |
  Test if the SAPHanaSR global.ini file configuration is properly done
remediation: |
  ## Remediation
  Set the recommended values in global.ini.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability#implement-the-python-system-replication-hook-saphanasr
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 2A4BEE
