---

id: 1.1.5.runtime
name: Corosync token_retransmits_before_loss_const parameter is set to {{ expected['1.1.5'] }} (runtime)
group: Corosync
labels: generic
description: |
  Test if the configured corosync token_retransmits_before_loss_const has the correct value during runtime: {{ expected['1.1.5'] }}
remediation: |
  ## Abstract
  The runtime value of the corosync `token_retransmits_before_loss_const` parameter is not set as recommended

  ## Remediation
  Adjust the corosync `token_retransmits_before_loss_const` parameter as recommended on the Azure best practices, and reload the corosync service.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
