---

- name: Set Test ID
  set_fact:
    test_id: '2.2.2'

- name: "{{ test_id }}.check"
  shell: |
    # Check OS version
    VERSION_ID=$(cat /etc/os-release | grep VERSION_ID= | sed "s/[^0-9]//g")
    [[ $VERSION_ID -ge "{{ expected[test_id] }}" ]] && exit 0
    exit 1
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
