---

- name: Set Test ID
  set_fact:
    test_id: '1.5.3'

- name: "{{ test_id }}.check"
  shell: |
          # The third field of ntpq -p is the stratum and if it's 16
          # the sync is disabled. Make sure it's not 16
          if ! sudo ntpq -pn | grep "No association ID's returned" \
          && sudo ntpq -pn | awk '{print $1 " " $3}' | grep -e '^\*' | awk '{print $2}' | grep -e "[0-9]" | grep -q -v 16; then
            if ps aux | grep "/usr/sbin/[n]tpd" | grep -q "\-x"; then exit 0; fi
          fi
          exit 1
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
