---

id: 2.1.8
name: SAPHanaSR sudoers configuration
group: SAP HANA System Replication Resource Agent
labels: hana
description: |
  Test if the sudoers file for the SAPHanaSR resource agent is properly configured
remediation: |
  ## Remediation
  Set up the sudoers entry to allow <sidadm> in /etc/sudoers to use the srHook.

  ## References
  - Section 8.3 in https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-allowing-sidadm-to-access-the-cluster
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
