---

name: 1.4.2
group: Azure Fence Agent
labels: generic
description: |
  Test if the concurrent fencing option is enabled
remediation: |
  ## Abstract
  Concurrent fencing must be enabled in order to use Azure Fence agent combined with SBD fencing.

  ## Remediation
  To enable it, run:
  ```
  crm configure property concurrent-fencing=true
  ```

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#1-create-the-stonith-devices
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 6E0DEC
