---

- name: Set Test ID
  set_fact:
    test_id: '2.2.3.exclude'

- name: "{{ test_id }}.check"
  shell: |
    # Check the pacemaker version IS NOT
    # If not installed, exit with error
    VERSION_ID=$(rpm -q --qf "%{VERSION}\n" pacemaker) || exit 2
    [[ "$VERSION_ID" != "{{ expected[test_id] }}" ]] && exit 0
    exit 1
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
