---
- name: Set Test ID
  set_fact:
    test_id: '1.2.2'

- name: "{{ test_id }}.check"
  shell: |
   timeout=$(crm_attribute -t crm_config -G -n stonith-timeout --quiet)
          if [[cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1 ]]; then
            if [[ "${timeout}" = "900" ]]; then
              echo "correct"
            else
              echo "${timeout}"
            fi
          elif [[ "${timeout}" = "144" ]]; then
            echo "correct"
          else
            echo "${timeout}"
          fi
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
