- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 1.2.2
    name: Fencing timeout is correctly configured
    group: Pacemaker
    labels: generic
    description: |
      Test if the configured cluster fencing option has the correct timeout
    remediation: |
      ## Abstract
      The fencing timeout (`stonith-timeout`) determines the time Pacemaker will wait for fencing to succeed.
      The recommended values on Azure are `144` seconds for SBD only or `900` seconds when using SBD combined with the Azure Fence agent.
      
      ## Remediation
      Execute the following command to adjust the timeout for your usecase:
      ```crm configure property stonith-timeout=144```
      or
      ```crm configure property stonith-timeout=900```

      ## References
      - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
    implementation: "{{ lookup('file', 'roles/'+id+'/tasks/main.yml') }}"
