---

name: 1.1.1.runtime
group: Corosync
labels: generic
description: |
  The configured corosync Token has the correct value during runtime: {{ expected['1.1.1'] }}
remediation: |
  ## Abstract
  The runtime value of the Corosync `token` timeout is not set as recommended.

  ## Remediation
  Adjust the corosync `token` timeout as recommended on the Azure best practices, and reload the corosync service

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 53D035
