---

id: 2.2.5
name: Check SBD version
group: OS and package versions
labels: hana
description: |
  Test if installed SBD version is supported
remediation: |
  ## Abstract
  Installed SBD version must be equal or higher than {{ expected['2.2.5'] }}

  ## Remediation
  Install or upgrade to a supported SBD version

  ## Reference
  - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
