definitions:
  models.ConnectionData:
    properties:
      id:
        type: string
      node:
        type: string
      user:
        type: string
    type: object
  web.JSONSelectedChecks:
    properties:
      selected_checks:
        items:
          type: string
        type: array
    required:
    - selected_checks
    type: object
  web.JSONTag:
    properties:
      tag:
        type: string
    required:
    - tag
    type: object
info:
  contact: {}
paths:
  /api/checks/{id}/connection_data:
    get:
      consumes:
      - application/json
      parameters:
      - description: Checks group id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ConnectionData'
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get users connection data
    post:
      consumes:
      - application/json
      parameters:
      - description: Checks group id
        in: path
        name: id
        required: true
        type: string
      - description: Checks connection user data
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ConnectionData'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create connection data for the node
  /api/checks/{id}/selected:
    get:
      consumes:
      - application/json
      parameters:
      - description: Resource id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.JSONSelectedChecks'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get selected checks from resource
    post:
      consumes:
      - application/json
      parameters:
      - description: Resource id
        in: path
        name: id
        required: true
        type: string
      - description: Selected checks
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONSelectedChecks'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONSelectedChecks'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create check selection for the resource
  /api/clusters/{cluster_id}/results:
    get:
      parameters:
      - description: Cluster Id
        in: path
        name: cluster_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a specific cluster's check results
  /api/clusters/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cluster id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to Cluster
  /api/clusters/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Cluster id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a cluster
  /api/databases/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Database id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to a HANA database
  /api/databases/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Database id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a HANA database
  /api/hosts/{name}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: Host name
        in: path
        name: name
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to host
  /api/hosts/{name}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Host name
        in: path
        name: name
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a host
  /api/sapsystems/{id}/tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: SAPSystem id
        in: path
        name: id
        required: true
        type: string
      - description: The tag to create
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.JSONTag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.JSONTag'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add tag to SAPSystem
  /api/sapsystems/{id}/tags/{tag}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: SAPSystem id
        in: path
        name: id
        required: true
        type: string
      - description: Tag
        in: path
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            additionalProperties: true
            type: object
      summary: Delete a specific tag that belongs to a SAPSystem
  /api/tags:
    get:
      consumes:
      - application/json
      parameters:
      - description: Filter by resource type
        in: query
        name: resource_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all the tags in the system
swagger: "2.0"
