apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ara.fullname" . }}-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.dataVolumeSize }}