apiVersion: v1
kind: Service
metadata:
  name: {{ include "ara.fullname" . }}
  labels:
    {{- include "ara.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ara-http
      protocol: TCP
      name: ara-http
  selector:
    {{- include "ara.selectorLabels" . | nindent 4 }}
