---

id: 2.2.4
name: Check corosync version
group: OS and package versions
labels: hana
description: |
  Test if installed Corosync version is supported
remediation: |
  ## Abstract
  Installed Corosync version must be equal or higher than {{ expected['2.2.4'] }}

  ## Remediation
  Install or upgrade to a supported Corosync version

  ## Reference
  - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
